import GoogleScraper as gs
import CombineSheets as cs
import pandas as pd
#IMPORT ALL FILES INTO THIS ONE SO THE COMPUTER CAN READ THE FILES QUICKLY
#WHERE ARE ALL THE KEYWORDS STORED, ENTER SHEET NAME
#MUST BE IN THE FIRST COLUMN WITH A HEADER
#!!!!!!!!!!!GOOGLE CAN REVOKE YOUR INTERNET SEARCH IF RUNNING THIS TO OFTEN!!!!!!!!!
df = pd.read_excel('fitness-keywords-wordstream.xlsx', sheet_name='sheet1')
#df = pd.read_excel('EXCEL_WORKBOOK_NAME.xlsx', sheet_name='SHEET_NAME')
#THIS LOOP WILL RUN A2 IN THE EXCEL FILE THEN THE NEXT ROW AND SO ON UNTIL INDEX 'I' IS NULL
for i in df.index:
    #df['Keyword'][i] IS THE DATAFRAME AND COLUMN NAME
    #COLUMN NAME MUST MATCH EXACTLY
    #SINGLE QUOTES IN COLUMN HEADER NAME ONLY
    gs.GoogleSearch(df['Keyword'][i])
#MERGES ALL SHEETS FROM GoogleScrapingSEOKEYFINDER.xlsx FOUND IN ROOT DIRECTORY WHICH CAN BE CHANGED IN COMBINE SHEET BUT YOU MUST
#SHANGE IT IN GOOGLESCRAPER ALSO !!!!!!!!!!!!!IMPORTANT!!!!!!!!!
cs.MergeAllDataSheets()
#EXCEL BOOK CLOSED YOU SHOULD NOW HAVE AN EXCEL SHEET THAT CONTAINS ALL SHEETS IN ONE SHEET
#INDEXING MUST BE CHANGED AND ORGINZED THE WAY YOU SEE FIT
#TRY FINDING THE NUMBER OF WORDS THAT MATCHED KEYWORDS SEARCHED TO DESCRIPTION WOULD BE A GOOD PLACE TO START
#COMPARE KEYWORD PHRASING TO TITLE, DESC, AND URL SEPERATLY

#AFTER RUNNING THIS MAIN CLASS FIND THE COUNTMASTERKEYWORDSTOEXCEL.PY RUN THIS TO MERGE ALL KEYWORD
#SHEETS INTO ONE THIS WILL ALLOW YOU HAVE ONE LARGE DOCUMENT THAT CONTAINS ALL SEARCH RESULTS
#INTO THE EXCEL FILE SOFTWAREENGINEERINGMASTERDATABASE.XLSX IN THIS CASE. IT CAN ALWAYS BE CHANGED
#RUNNING THIS FILE WILL TAKE AWHILE PLEASE BE CAREFUL AND PATIENT ON HOW OFTEN YOU USE IT.

#IF YOU GET RECOVERED DOCUMENT OR BROKEN DOCUMENT JUST ALLOW EXCEL TO REMOVE BROKEN DATA IT IS OKAY!

#AFTERRUNNING THIS DOCUMENT YOU MUST CLEAN THE DATA BEFORE RUNNING THE COUNTMASTERKEYWORDSTOEXCEL.PY DOCUMENT!


#DELETE NULL VALUES, NUMERIC VALUES, OR BROKEN URL STATEMENTS.
